language: node_js

node_js:
 - "0.12"

branches:
  except:
    - beta

# Using faster container based build environment.

sudo: false

before_script:
 - npm install npm

script:
 - npm test

notifications:
  irc:
    channels:
      - "chat.freenode.net#dat"
    on_success: change
    on_failure: change
