language: node_js

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

node_js:
  - "4"
  - "6"
  - "8"

sudo: false

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX=g++-4.8; fi

script:
 - npm test

notifications:
  irc:
    channels:
      - "chat.freenode.net#datbots"
    template:
      - "%{repository_slug} - %{commit_subject} - %{result} - %{build_url}"
    skip_join: true
    on_success: change
    on_failure: always

