site_name: Dat project
theme: readthedocs
pages:
- Home: 'index.md'
- User Guide: 'user-guide.md'
- Commandline API: 'cli-docs.md'
- Hosting a Dat: 'hosting.md'
- Technical Guide: 'technical-guide.md'
- Meta:
  - 'Changelog': 'meta/changelog.md'
  - 'Roadmap': 'meta/roadmap.md'
  - 'Collaborators': 'meta/collaborators.md'
  - 'Talks': 'meta/talks.md'
extra_css: [extra.css]
